language: python 
python: 
- "3.7"
env: 
- DJANGO=2.0 DB=pabcubcrudb
dist: xenial
services:
  - postgresql
addons:
  postgresql: "9.6"
global:
  - PGPORT=5432
before_install:
- cd decide
install:
  - pip install -r ../requirements.txt
before_script:
  - cp travis_local_settings.py local_settings.py
  - psql -U postgres -c "create user pabcubcru password 'pabcubcru'"
  - psql -U postgres -c "create database pabcubcrudb owner pabcubcru"
  - psql -U postgres -c "ALTER USER pabcubcru CREATEDB"
  - python manage.py migrate
script:
  - python manage.py test voting
notifications:
 email: 
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  app: pabcubcruexamen1230
  strategy: git
  api_key: $HEROKU_AUTH_TOKEN



